# NOTE: *MUST* change to your own username (also IRC nick) and email address
KB_USERNAME ?= no_more_than_9-chars_is_best
KB_EMAIL ?= 9_char_nick@example.com
export

all:
	$(MAKE) -f linux.mk $@
kybyz.%: .FORCE
	$(MAKE) -f linux.mk $@
%:
	$(MAKE) -f linux.mk $@
.FORCE:
	true  # so as to avoid `make -f linux.mk .FORCE`
